In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, SubsetRandomSampler

# https://towardsdatascience.com/pytorch-vision-binary-image-classification-d9a227705cf9 

In [2]:
class CustomDataset(Dataset):
    
    def __init__(self, X_data, y_data):
        self.X_data = X_data
        self.y_data = y_data
        
    def __getitem__(self, index):
        return self.X_data[index], self.y_data[index]
        
    def __len__ (self):
        return len(self.X_data)
    

In [3]:
X = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y= [0, 0, 0, 1, 0, 1, 1, 0, 0, 1]
data = CustomDataset(torch.FloatTensor(X), torch.FloatTensor(y))

#data.__len__()#10
#data.__getitem__(2) #(tensor(3.), tensor(0.))

data_loader = DataLoader(dataset=data, batch_size=2, shuffle=True)
data_loader_iter = iter(data_loader)
print(next(data_loader_iter))


for i,j in data_loader:
    print(i,j)


[tensor([3., 9.]), tensor([0., 0.])]
tensor([6., 9.]) tensor([1., 0.])
tensor([10.,  7.]) tensor([1., 1.])
tensor([3., 5.]) tensor([0., 0.])
tensor([4., 2.]) tensor([1., 0.])
tensor([8., 1.]) tensor([0., 0.])


In [4]:
###############
## Regression

y_pred = torch.tensor([[1.2, 2.3, 3.4], [4.5, 5.6, 6.7]], requires_grad=True)
print("Y Pred: \n", y_pred)
print("\nY Pred shape: ", y_pred.shape, "\n")
print("=" * 50)
y_train = torch.tensor([[1.2, 2.3, 3.4], [7.8, 8.9, 9.1]])
print("\nY Train: \n", y_train)
print("\nY Train shape: ", y_train.shape)

Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000],
        [4.5000, 5.6000, 6.7000]], requires_grad=True)

Y Pred shape:  torch.Size([2, 3]) 


Y Train: 
 tensor([[1.2000, 2.3000, 3.4000],
        [7.8000, 8.9000, 9.1000]])

Y Train shape:  torch.Size([2, 3])


In [5]:
### Mean Absolute Error — torch.nn.L1Loss()
mae_loss = nn.L1Loss()
print("Y Pred: \n", y_pred)
print("Y Train: \n", y_train)
output = mae_loss(y_pred, y_train)
print("MAE Loss\n", output)
output.backward()



Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000],
        [4.5000, 5.6000, 6.7000]], requires_grad=True)
Y Train: 
 tensor([[1.2000, 2.3000, 3.4000],
        [7.8000, 8.9000, 9.1000]])
MAE Loss
 tensor(1.5000, grad_fn=<L1LossBackward>)


In [6]:
############################
### Binary Classification
# y_train has two classes - 0 and 1. 
# We use this BCE loss function in the situation when the final output 
# from the network is a single value (final dense layer is of size 1) that lies between 0 and 1.


y_pred = torch.tensor([[1.2, 2.3, 3.4], [7.8, 8.9, 9.1]], requires_grad = True)
print("Y Pred: \n", y_pred)
print("\nY Pred shape: ", y_pred.shape, "\n")
print("=" * 50)
y_train = torch.tensor([[1, 0, 1], [0, 0, 1]])
print("\nY Train: \n", y_train)
print("\nY Train shape: ", y_train.shape)



Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000],
        [7.8000, 8.9000, 9.1000]], requires_grad=True)

Y Pred shape:  torch.Size([2, 3]) 


Y Train: 
 tensor([[1, 0, 1],
        [0, 0, 1]])

Y Train shape:  torch.Size([2, 3])


In [7]:

#Binary Cross Entropy Loss — torch.nn.BCELoss()
bce_loss = nn.BCELoss()
y_pred_sigmoid = torch.sigmoid(y_pred)
print("Y Pred: \n", y_pred)
print("\nY Pred Sigmoid: \n", y_pred_sigmoid)
print("\nY Train: \n", y_train.float())
output = bce_loss(y_pred_sigmoid, y_train.float())
print("\nBCE Loss\n", output)
output.backward()


Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000],
        [7.8000, 8.9000, 9.1000]], requires_grad=True)

Y Pred Sigmoid: 
 tensor([[0.7685, 0.9089, 0.9677],
        [0.9996, 0.9999, 0.9999]], grad_fn=<SigmoidBackward>)

Y Train: 
 tensor([[1., 0., 1.],
        [0., 0., 1.]])

BCE Loss
 tensor(3.2321, grad_fn=<BinaryCrossEntropyBackward>)


In [8]:
#############################
# Binary Cross Entropy with Logits Loss — torch.nn.BCEWithLogitsLoss()
# The input and output have to be the same size and have the dtype float. 
# This class combines Sigmoid and BCELoss into a single class. 
# This version is numerically more stable than using Sigmoid and BCELoss individually.

bce_logits_loss = nn.BCEWithLogitsLoss()
print("Y Pred: \n", y_pred)
print("\nY Train: \n", y_train.float())
output = bce_logits_loss(y_pred, y_train.float())
print("\nBCE Loss\n", output)
output.backward()


Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000],
        [7.8000, 8.9000, 9.1000]], requires_grad=True)

Y Train: 
 tensor([[1., 0., 1.],
        [0., 0., 1.]])

BCE Loss
 tensor(3.2321, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)


In [9]:
################################
################################
################################
################################
## Multiclass Classification
# Let’s define the actual and predicted output tensors in order to calculate the loss.
# y_train has 3 classes 0, 1, 2, and 3.

y_pred = torch.tensor([[1.2, 2.3, 3.4, 1.0], [4.5, 5.6, 6.7, 1.0], [7.8, 8.9, 9.1, 1.0], [7.8, 8.9, 9.1, 1.0]], requires_grad = True)
print("Y Pred: \n", y_pred)
print("\nY Pred shape: ", y_pred.shape, "\n")
print("=" * 50)
y_train = torch.tensor([0, 1, 2, 3])
print("\nY Train: \n", y_train)
print("\nY Train shape: ", y_train.shape)


Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000, 1.0000],
        [4.5000, 5.6000, 6.7000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000]], requires_grad=True)

Y Pred shape:  torch.Size([4, 4]) 


Y Train: 
 tensor([0, 1, 2, 3])

Y Train shape:  torch.Size([4])


In [10]:
# Negative Log Likelihood — torch.nn.NLLLoss()

nll_loss = nn.NLLLoss()
y_pred_logsoftmax = torch.log_softmax(y_pred, dim = 1)
print("Y Pred: \n", y_pred)
print("\nY Pred LogSoftmax: \n", y_pred_logsoftmax)
print("\nY Train: \n", y_train)
output = nll_loss(y_pred_logsoftmax, y_train)
print("\nNLL Loss\n", output)
output.backward()

Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000, 1.0000],
        [4.5000, 5.6000, 6.7000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000]], requires_grad=True)

Y Pred LogSoftmax: 
 tensor([[-2.6281, -1.5281, -0.4281, -2.8281],
        [-2.5695, -1.4695, -0.3695, -6.0695],
        [-2.0379, -0.9379, -0.7379, -8.8379],
        [-2.0379, -0.9379, -0.7379, -8.8379]], grad_fn=<LogSoftmaxBackward>)

Y Train: 
 tensor([0, 1, 2, 3])

NLL Loss
 tensor(3.4184, grad_fn=<NllLossBackward>)


In [11]:
# CrossEntropyLoss — torch.nn.CrossEntropyLoss()
# This class combines LogSoftmax and NLLLoss into a single class.

ce_loss = nn.CrossEntropyLoss()
print("Y Pred: \n", y_pred)
print("\nY Train: \n", y_train)
output = ce_loss(y_pred, y_train)
print("\nNLL Loss\n", output)
output.backward()

Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000, 1.0000],
        [4.5000, 5.6000, 6.7000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000]], requires_grad=True)

Y Train: 
 tensor([0, 1, 2, 3])

NLL Loss
 tensor(3.4184, grad_fn=<NllLossBackward>)
