In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, SubsetRandomSampler

# https://towardsdatascience.com/pytorch-vision-binary-image-classification-d9a227705cf9 

In [2]:
############################
### Binary Classification
# y_train has two classes - 0 and 1. 
# We use this BCE loss function in the situation when the final output 
# from the network is a single value (final dense layer is of size 1) that lies between 0 and 1.


y_pred = torch.tensor([[1.2, 2.3, 3.4], [7.8, 8.9, 9.1]], requires_grad = True)
print("Y Pred: \n", y_pred)
print("\nY Pred shape: ", y_pred.shape, "\n")
print("=" * 50)
y_train = torch.tensor([[1, 0, 1], [0, 0, 1]])
print("\nY Train: \n", y_train)
print("\nY Train shape: ", y_train.shape)



Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000],
        [7.8000, 8.9000, 9.1000]], requires_grad=True)

Y Pred shape:  torch.Size([2, 3]) 


Y Train: 
 tensor([[1, 0, 1],
        [0, 0, 1]])

Y Train shape:  torch.Size([2, 3])


In [3]:

#Binary Cross Entropy Loss — torch.nn.BCELoss()
bce_loss = nn.BCELoss()
y_pred_sigmoid = torch.sigmoid(y_pred)
print("Y Pred: \n", y_pred)
print("\nY Pred Sigmoid: \n", y_pred_sigmoid)
print("\nY Train: \n", y_train.float())
output = bce_loss(y_pred_sigmoid, y_train.float())
print("\nBCE Loss\n", output)
output.backward()


Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000],
        [7.8000, 8.9000, 9.1000]], requires_grad=True)

Y Pred Sigmoid: 
 tensor([[0.7685, 0.9089, 0.9677],
        [0.9996, 0.9999, 0.9999]], grad_fn=<SigmoidBackward>)

Y Train: 
 tensor([[1., 0., 1.],
        [0., 0., 1.]])

BCE Loss
 tensor(3.2321, grad_fn=<BinaryCrossEntropyBackward>)


In [4]:
#############################
# Binary Cross Entropy with Logits Loss — torch.nn.BCEWithLogitsLoss()
# The input and output have to be the same size and have the dtype float. 
# This class combines Sigmoid and BCELoss into a single class. 
# This version is numerically more stable than using Sigmoid and BCELoss individually.

bce_logits_loss = nn.BCEWithLogitsLoss()
print("Y Pred: \n", y_pred)
print("\nY Train: \n", y_train.float())
output = bce_logits_loss(y_pred, y_train.float())
print("\nBCE Loss\n", output)
output.backward()


Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000],
        [7.8000, 8.9000, 9.1000]], requires_grad=True)

Y Train: 
 tensor([[1., 0., 1.],
        [0., 0., 1.]])

BCE Loss
 tensor(3.2321, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)


In [5]:
################################
################################
################################
################################
## Multiclass Classification
# Let’s define the actual and predicted output tensors in order to calculate the loss.
# y_train has 4 classes 0, 1, 2, and 3.

y_pred = torch.tensor([[1.2, 2.3, 3.4, 1.0], [4.5, 5.6, 6.7, 1.0], [7.8, 8.9, 9.1, 1.0], [7.8, 8.9, 9.1, 1.0]], requires_grad = True)
print("Y Pred: \n", y_pred)
print("\nY Pred shape: ", y_pred.shape, "\n")
print("=" * 50)
y_train = torch.tensor([0, 1, 2, 3])
print("\nY Train: \n", y_train)
print("\nY Train shape: ", y_train.shape)


Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000, 1.0000],
        [4.5000, 5.6000, 6.7000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000]], requires_grad=True)

Y Pred shape:  torch.Size([4, 4]) 


Y Train: 
 tensor([0, 1, 2, 3])

Y Train shape:  torch.Size([4])


In [6]:
# # CrossEntropyLoss — torch.nn.CrossEntropyLoss()
# # This class combines LogSoftmax and NLLLoss into a single class.

ce_loss = nn.CrossEntropyLoss()
print("Y Pred: \n", y_pred)
print("\nY Train: \n", y_train)
output = ce_loss(y_pred, y_train)
# print("\nNLL Loss\n", output)
# output.backward()

Y Pred: 
 tensor([[1.2000, 2.3000, 3.4000, 1.0000],
        [4.5000, 5.6000, 6.7000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000],
        [7.8000, 8.9000, 9.1000, 1.0000]], requires_grad=True)

Y Train: 
 tensor([0, 1, 2, 3])
